name: PR

on: [pull_request]

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # GitVersion action doesn't support /ensureassemblyinfo, see https://github.com/GitTools/actions/issues/220
      # So we need to create a new file to let GitVersion populate it
      - name: Create assembly info file for GitVersion
        shell: powershell
        run: |
          set-Content -Path 'Blish HUD/Properties/AssemblyVersionInfo.cs' -Value 'using System.Reflection;'
      - uses: gittools/actions/gitversion/setup@v0.9.6
        with:
          versionSpec: '5.x'

      - uses: gittools/actions/gitversion/execute@v0.9.6
        id: gitversion
        with:
          updateAssemblyInfo: true
          updateAssemblyInfoFilename: Blish HUD/Properties/AssemblyVersionInfo.cs

      - name: Run dotnet restore
        run: dotnet restore
      - name: Run dotnet publish
        run: dotnet publish -c Release -p:VERSIONED_BUILD=${{ steps.gitversion.outputs.semVer }} -o publish
      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: Blish HUD.${{ steps.gitversion.outputs.semVer }}
          path: publish/**
