name: TAG

on:
  push:
    tags:
      - '*'

jobs:
  nightly:
    name: Nightly
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - run: git fetch --prune --unshallow

      - name: Patch nightly version
        shell: powershell
        run: |
          $version = GitVersion /output json /updateassemblyinfo "Blish HUD/Properties/AssemblyVersionInfo.cs" /ensureassemblyinfo
          Write-Output $version
          $version = $version | ConvertFrom-Json
          $nuget = $version.SemVer
          Write-Output "Assembly version: $($version.AssemblySemVer)"
          Write-Output "Assembly file version: $($version.AssemblySemFileVer)"
          Write-Output "Informational version: $($version.InformationalVersion)"
          Write-Output "NuGet version: $nuget"
          echo "::set-env name=VERSION::$nuget"

      - name: Run dotnet restore
        run: dotnet restore
      - name: Run dotnet publish
        run: dotnet publish "Blish HUD" -c Release -p:VERSIONED_BUILD=$env:VERSION
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: Blish HUD ${{ env.VERSION }}
          path: Blish HUD/bin/x64/Release/**

      - name: Run dotnet pack
        run: dotnet pack -c Release -p:VERSIONED_BUILD=$env:VERSION -o pack
      - name: Upload NuGet package artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Blish HUD ${{ env.VERSION }} NuGet packages
          path: Blish HUD/bin/Release/BlishHUD.${{ env.VERSION }}.*nupkg
